{{ if not (empty .Values.config.configFile) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.secretName }}
type: Opaque
stringData:
{{ .Values.config.configFile | toYaml | indent 2}}
{{ end }}