apiVersion: v1
kind: Service
metadata:
  name: {{ include "azure_metrics_exporter.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: {{ include "azure_metrics_exporter.name" . }}
    helm.sh/chart: {{ include "azure_metrics_exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "azure_metrics_exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}