apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azure_metrics_exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "azure_metrics_exporter.name" . }}
    helm.sh/chart: {{ include "azure_metrics_exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "azure_metrics_exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ toYaml .Values.configuration | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "azure_metrics_exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.labels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      volumes:
      - name: config-volume
        secret:
          secretName: {{ .Values.config.secretName }}
    {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
    {{- end }}
      containers:
      - name: azure-metrics-exporter
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: config-volume
          mountPath: {{ .Values.config.secretMountPath}}
          readOnly: true
        ports:
        - name: http
          containerPort: 9276
          protocol: TCP
        workingDir: {{ .Values.config.secretMountPath}}
        # command: [ "/bin/sh", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
        resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}